### PR TITLE
Fix switch-frame handling.

### PR DESCRIPTION
**Pull request by jhonnyseven**
Calling only `hydra-keyboard-quit' on switch-frame event was
effectively stopping the original frame switch. This change adds a
call to the original handler after calling `hydra-keyboard-quit'.

See #73

* hydra.el: Add `hydra--handle-switch-frame'

* hydra-test.el: Update

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks, the change looks reasonable.

However, it is over 15 lines, and since hydra is in GNU ELPA, you'll need to sign
[the FSF Copyright Papers](http://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html) before I can merge it.

**Comment by jhonnyseven** [comment]
I think it's ok, from https://www.gnu.org/prep/maintain/html_node/Legally-Significant.html#Legally-Significant:
"A change of just a few lines (less than 15 or so) is not legally significant for copyright. __A regular series of repeated changes, such as renaming a symbol, is not legally significant even if the symbol has to be renamed in many places.__[...]"

**Comment by abo-abo** [comment]
> I think it's ok

Alright, but you'll need the assignment for the next (hopfully, there will be) change. I don't want to get in trouble with the Emacs guys:)

**Comment by jhonnyseven** [comment]
Fair enough :)
What is the project name if I wanted to sign those papers? GNU ELPA or hydra or what?

**Comment by abo-abo** [comment]
I signed it for general Emacs.

**Pull request closed without merging**
