### PR TITLE
RFC for #147 - implementation of named column

### PR DESCRIPTION
**Pull request by Mugu-Mugu**
This is a first rough and naive implementation for #147 to gather early reviews. 

**Non regression : 17/34 OK**

**Diff with code snippet from #147**:
- Dash dependencies removed
- slight refactoring

**Need reviews of at least following points:**
- integration strategy
- reuse/merge of/with existing function
- naming
- code style

**Todo**
- investigate and fix regressions
- add tests
- improve code
- update wiki

By the way, this is the first pull request I open so please tell me if there is anything wrong

### CODE REVIEW

**Comment by abo-abo** [comment]
The PR looks good so far. It's strange to me that it breaks some tests though.

Seems to me if you detect that `:column` isn't used in any head, you can redirect to the old code, thus solving all the failing tests.

**Comment by Mugu-Mugu** [comment]
Well, there was a redirection to old code... but prepended with a "\n" :p 
So in the end, it was only minor string formating issues. Now everything seems ok and still renders well on my end. 
I'm sending the form for the CA and I'll add some basic tests later.

**Comment by abo-abo** [comment]
Thanks.

**Comment by Mugu-Mugu** [comment]
Small update:
I have received the papers for the CA. It seems a scanned copy is enough so it may be faster than expected. Maybe I'll have it by the end of the week.

**Comment by abo-abo** [comment]
Thanks. For which country a scanned copy is enough?

**Comment by Mugu-Mugu** [comment]
It's recent but it looks like it can be done from any country now:
https://www.fsf.org/blogs/licensing/fsf-now-offering-paperless-option-for-all-copyright-assignments

**Comment by abo-abo** [comment]
Nice. I'll make sure to mention that link to new people.

**Comment by Mugu-Mugu** [comment]
Hello, I have received my CA at the beginning of this week. Despite the electronic process, it can still take some time (but it wasn't really an issue as I didn't have much spare time anyway).

Back to the PR, I have merged it with the last master commit. What is the next step?

**Comment by abo-abo** [comment]
Thank you for the contribution. I've reviewed and merged your code.

Some notes:

- It's best to rebase the PR on top of master, never merge.
- See the `checkdoc` command for automated suggestions on Elisp docstring style.

Also, the test that you added has trailing spaces inside a string. This is problematic for me because I have `(add-hook 'before-save-hook 'delete-trailing-whitespace)`.
Could you please update the code so that the hydra docstrings don't have trailing whitespace?

**Comment by Mugu-Mugu** [comment]
Thanks for the advices. I'll reactivate flycheck-checkdoc so I don't miss this the next time.

I'll open another PR for the trailing whitespace.

**Pull request closed without merging**
